site_name: pybrook

nav:
  - Main: "index.md"

theme:
  name: "material"
  language: en
  palette:
    primary: white
    accent: pink

extra_css:
  - css/mkdocstrings.css

extra:
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
      guess_lang: false
  - admonition
  - footnotes
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - git-revision-date-localized
  - mkdocstrings:
      watch:
        - .
      handlers:
        python:
          rendering:
            show_if_no_docstring: true
          selection:
            filters:
              - "!^__config__"
              - "!^__json_encoder__"